wechat_id: bj-mini4wd
help_message: help
welcome_message:
  title: 欢迎加入北京站！
  picture: https://mmbiz.qlogo.cn/mmbiz/SqapgC1ALbeOX4UcfnpM6449fQwLJx2tic7gLoFPnuq6N5BjjbD8cQxsnZzPiaOT8iag3zpLswYVwoHhgVGDEoMDg/0
  description: 感谢您订阅【北京站】官方微信号！这里是田宫迷你四驱车北京地区玩家俱乐部。
  #link: linkedme.in/2013/09/25/turoial-to-be-wechat-public-account-developer/
