wechat_id: bj-mini4wd
welcome_message: |
  感谢您订阅【北京站】官方微信号！这里是田宫迷你四驱车北京地区玩家俱乐部，您可以回复以下数字了解详情：
  1：查看车场简介、位置；
  2：查看车场资费；
  3：查看近期活动安排；
  4：查看田宫比赛规则。
info_message: 车场简介
cost_message: 车场资费
note_message: 近期活动
rule_message: 比赛规则