wechat_id: bj-mini4wd
help_message: help
welcome_message:
  title: 欢迎加入北京站！
  picture: https://mmbiz.qlogo.cn/mmbiz/SqapgC1ALbeOX4UcfnpM6449fQwLJx2tic7gLoFPnuq6N5BjjbD8cQxsnZzPiaOT8iag3zpLswYVwoHhgVGDEoMDg/0
  description: >
  	感谢您订阅【北京站】官方微信号！这里是田宫迷你四驱车北京地区玩家俱乐部，您可以回复以下数字了解详情：
  	1：查看车场简介、位置；
  	2：查看车场资费；
  	3：查看近期活动；
  	4：查看比赛规则。
  link: linkedme.in/2013/09/25/turoial-to-be-wechat-public-account-developer/
